---
- name: Prepare
  hosts: node*
  become: true
  tasks:
    - name: Install wget for Ubuntu
      ansible.builtin.package:
        update_cache: true
        name:
          - wget
      when: ansible_distribution == "Ubuntu"

    - name: Install iproute for RockyLinux
      ansible.builtin.package:
        update_cache: true
        name:
          - iproute
      when: ansible_distribution == "Rocky"
