# /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
# https://docs.rke2.io/networking/basic_network_options
# https://github.com/rancher/rke2-charts/tree/main/charts/rke2-cilium/rke2-cilium/1.15.600
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: 192.168.178.240
    k8sServicePort: 6443
    encryption:
      enabled: true
      type: wireguard
      nodeEncryption: true
      strictMode:
        enabled: true
        cidr: "10.100.0.0/16"
    bpf:
      masquerade: true  
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList: "[10.100.0.0/16]"
        clusterPoolIPv4MaskSize: 24
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
