---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: 192.168.178.240
    k8sServicePort: 6443
    nodePort:
      enabled: true
    envoy:
      enabled: true
    debug:
      enabled: true
    cluster:
      name: rino
    ipMasqAgent:
      enabled: false
    endpointRoutes:
      enabled: true
    rollOutCiliumPods: true
    certgen:
      tolerations:
        - operator: Exists
    encryption:
      enabled: true
      type: wireguard
      nodeEncryption: true
      strictMode:
        enabled: true
        cidr: 10.0.0.0/8
    bpf:
      masquerade: true  
      hostLegacyRouting: false
      datapathMode: veth
    routingMode: tunnel
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.0.0.0/8
        clusterPoolIPv4MaskSize: 24
    hubble:
      enabled: true
      tls:
        enabled: true
        auto:
          enabled: true
          method: cronJob
      relay:
        enabled: true
        rollOutPods: true
      ui:
        enabled: true
        rollOutPods: true
      tolerations:
        - oprator: Exists
    loadBalancer:
      l7:
        backend: envoy

        
