- name: Deploy RKE2
  hosts: all
  become: yes
  vars:
    rke2_disable_cloud_controller: true
    rke2_download_kubeconf_path: "$PWD"
    rke2_ha_mode: true
    rke2_api_ip : 192.168.178.240
    rke2_download_kubeconf: true
    rke2_version: v1.32.3+rke2r1
    disable_kube_proxy: true
    rke2_cluster_cidr:
      - 10.0.0.0/8
    rke2_service_cidr:
      - 172.16.0.0/16
    rke2_cni:
       - cilium
    rke2_custom_manifests:
      - templates/rke2-cilium-config.yaml
  roles:
     - role: lablabs
